PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX dct: <http://purl.org/dc/terms/> 
PREFIX lexid-s: <https://w3id.org/lex-id/schema/> 
PREFIX lexid: <https://w3id.org/lex-id/data/> 
SELECT distinct ?answer
WHERE {
    ?LegalDocument a lexid-s:LegalDocument ;
    rdfs:label "legal_title"^^xsd:string ;
    lexid-s:hasContent/lexid-s:hasPart* [
        a lexid-s:Article ;
        rdfs:label "pasal_num"^^xsd:string ;
        lexid-s:hasPart [
            a lexid-s:Section ;
            rdfs:label "ayat_num"^^xsd:string ;
            dct:description ?answer ;
        ] ;
    ] .
}